---
- name: ensure cinder.conf is properly configured
  ini_file:
    dest: /etc/cinder/cinder.conf
    group: cinder
    mode: 0640
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: DEFAULT, option: log_dir, value: /var/log/cinder }
    - { section: DEFAULT, option: verbose, 
        value: "{{ openstack_log_verbose }}" }
    - { section: DEFAULT, option: debug, value: "{{ openstack_log_debug }}" }
    - { section: DEFAULT, option: rpc_backend, value: rabbit }
    - { section: DEFAULT,
        option: rabbit_host, value: "{{ openstack_rabbitmq_host }}" }
    - { section: DEFAULT, option: rabbit_port,
        value: "{{ openstack_rabbitmq_port }}" }
    - { section: DEFAULT, option: rabbit_userid, value: cinder }
    - { section: DEFAULT, option: rabbit_password,
        value: "{{ openstack_rabbitmq_cinder_password }}" }
    - { section: DEFAULT, option: rabbit_virtual_host, value: /cinder }
    - { section: database, option: connection,
        value: "mysql://cinder:{{ openstack_mysql_cinder_password }}@{{ 
                  openstack_mysql_host }}:{{ openstack_mysql_port }}/cinder" }
    - { section: DEFAULT, option: glance_host,
        value: "{{ openstack_image_endpoint_host }}" }
    - { section: DEFAULT,
        option: my_ip, value: "{{ openstack_volume_node_ip }}" }
    - { section: keystone_authtoken, option: auth_uri, 
        value: "{{ openstack_identity_internal_url }}" }
    - { section: keystone_authtoken, option: auth_host, 
        value: "{{ openstack_identity_endpoint_host }}" }
    - { section: keystone_authtoken, option: auth_port, value: 35357 }
    - { section: keystone_authtoken, option: auth_protocol, value: http }
    - { section: keystone_authtoken, option: admin_tenant_name, value: service }
    - { section: keystone_authtoken, option: admin_user, value: cinder }
    - { section: keystone_authtoken, option: admin_password, 
        value: "{{ openstack_identity_cinder_password }}" }
  register: modify_cinder_ini

- name: ensure cinder database has been synced
  sudo_user: cinder
  command: /usr/bin/cinder-manage db sync
  when: create_cinder_db|changed or modify_cinder_ini|changed
  failed_when: false

- name: restart cinder services if necessary
  service:
    name: "{{ item }}"
    state: restarted
  with_items: openstack_cinder_services
  when: modify_cinder_ini|changed

- name: ensure cinder sqlite is deleted
  file:
    dest: /var/lib/cinder/cinder.sqlite
    state: absent
